from PyQt6.QtWidgets import QComboBox


class CharacterDropdown(QComboBox):
    def __init__(self):
        super().__init__()

        self.addItems(
            [
                "01-Mario",
                "02-Donkey Kong",
                "03-Link",
                "04-Samus",
                "04x-Dark Samus",
                "05-Yoshi",
                "06-Kirby",
                "07-Fox",
                "08-Pikachu",
                "09-Luigi",
                "10-Ness",
                "11-Captain Falcon",
                "12-Jigglypuff",
                "13-Peach",
                "13x-Daisy",
                "14-Bowser",
                "15-Ice Climbers",
                "16-Sheik",
                "17-Zelda",
                "18-Dr. Mario",
                "19-Pichu",
                "20-Falco",
                "21-Marth",
                "21x-Lucina",
                "22-Young Link",
                "23-Ganondorf",
                "24-Mewtwo",
                "25-Roy",
                "25x-Chrom",
                "26-Mr. Game and Watch",
                "27-Meta Knight",
                "28-Pit",
                "28x-Dark Pit",
                "29-Zero Suit Samus",
                "30-Wario",
                "31-Snake",
                "32-Ike",
                "33-35-Pokemon Trainer",
                "33-Squirtle",
                "34-Ivysaur",
                "35-Charizard",
                "36-Diddy Kong",
                "37-Lucas",
                "38-Sonic",
                "39-King Dedede",
                "40-Olimar",
                "41-Lucario",
                "42-R.O.B",
                "43-Toon Link",
                "44-Wolf",
                "45-Villager",
                "46-Mega Man",
                "47-Wii Fit Trainer",
                "48-Rosalina and Luma",
                "49-Little Mac",
                "50-Greninja",
                "51-Mii Brawler",
                "52-Mii Swordfighter",
                "53-Mii Gunner",
                "54-Palutena",
                "55-Pac-Man",
                "56-Robin",
                "57-Shulk",
                "58-Bowser Jr",
                "59-Duck Hunt",
                "60-Ryu",
                "60x-Ken",
                "61-Cloud",
                "62-Corrin",
                "63-Bayonetta",
                "64-Inkling",
                "65-Ridley",
                "66-Simon",
                "66x-Richter",
                "67-King K. Rool",
                "68-Isabelle",
                "69-Incineroar",
                "70-Piranha Plant",
                "71-Joker",
                "72-Hero",
                "73-Banjo and Kazooie",
                "74-Terry",
                "75-Byleth",
                "76-Min Min",
                "77-Steve",
                "78-Sephiroth",
                "79-Pyra Mythra",
                "80-Kazuya",
                "82-Sora",
                "Random",
            ]
        )
