on:
    release:
      types: [published]
name: Handle Release      
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'GraphicAssembler-$GITHUB_REF'
      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/
          tag: $GITHUB_REF
